In [85]:
import sys
import numpy as np
sys.path.insert(0, '/home/nkotelevskii/github/corrected_l2hmc/l2hmc_pytorch/l2hmc/utils/')
from dynamics_pt import Dynamics
import torch
import torch.nn as nn

In [7]:
cl = Dynamics(2, None)

In [8]:
cl.temperature

tensor(5.)

In [9]:
cl.eps

Parameter containing:
tensor(0.1000, requires_grad=True)

In [16]:
a = torch.tensor(np.arange(12).reshape(3, 1, 4))
a

tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

In [17]:
a[2, ...]

tensor([[ 8,  9, 10, 11]])

In [23]:
a.repeat(2, 1, 1).shape

torch.Size([6, 1, 4])

In [28]:
torch.randn(a.shape).shape

torch.Size([3, 1, 4])

In [50]:
tuple(a.shape)

(3, 1, 4)

In [33]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
t = torch.tensor(0.)
while t < 10:
    t += 1
t

tensor(10.)

In [51]:
torch.tensor([1, 2, 4.])

tensor([1., 2., 4.])

In [79]:
def func(xx):
    cc = 2 * xx**2
    gg =3 * cc
    return gg

In [80]:
x = torch.autograd.Variable(torch.rand(5), requires_grad=True)
print('x', x)
y = torch.sum(func(x))
deriv = torch.autograd.grad(y, x)
deriv

x tensor([0.5901, 0.9670, 0.0363, 0.6394, 0.7514], requires_grad=True)


(tensor([ 7.0811, 11.6041,  0.4354,  7.6729,  9.0168]),)

In [81]:
deriv[0].shape

torch.Size([5])

In [84]:
[1, 2, 3][:-1]

[1, 2]

In [127]:
from collections import OrderedDict
import itertools

In [128]:
net1 = nn.Sequential(OrderedDict([('lin1', nn.Linear(1, 2)), ('relu', nn.ReLU()), ('lin2', nn.Linear(2, 1))]))
net2 = nn.Sequential(OrderedDict([('lin1', nn.Linear(1, 2)), ('relu', nn.ReLU()), ('lin2', nn.Linear(2, 1))]))

optim = torch.optim.Adam(itertools.chain(net1.parameters(), net2.parameters()))
scheduler = torch.optim.lr_scheduler.StepLR(optim, step_size=10, gamma=0.5)

In [129]:
x_train = torch.rand((100, 1))
y_train = x_train.sum(dim=1)**2 + 0.01 * torch.randn(x_train.shape[0])

In [130]:
n_epoches = 100
for i in range(n_epoches):
    optim.zero_grad()
    answ = x_train
    answ1 = answ
    answ2 = answ
    for t in range(3):
        answ1 = net1(answ1)
    for t in range(3):
        answ2 = net2(answ2)
        
    loss = torch.mean(((y_train) ** 8 - answ1 - answ2)**2)
    print('loss', loss)
    print('before backward', net.lin1.bias.grad)
    loss.backward()
    print('after backward', net.lin1.bias.grad)
    optim.step()
    scheduler.step()
    for param_group in optim.param_groups:
        current_lr = param_group['lr']
        print('current_lr', current_lr)

loss tensor(0.0097, grad_fn=<MeanBackward0>)
before backward tensor([0.4995, 0.0000])
after backward tensor([0.4995, 0.0000])
current_lr 0.001
loss tensor(0.0096, grad_fn=<MeanBackward0>)
before backward tensor([0.4995, 0.0000])
after backward tensor([0.4995, 0.0000])
current_lr 0.001
loss tensor(0.0094, grad_fn=<MeanBackward0>)
before backward tensor([0.4995, 0.0000])
after backward tensor([0.4995, 0.0000])
current_lr 0.001
loss tensor(0.0093, grad_fn=<MeanBackward0>)
before backward tensor([0.4995, 0.0000])
after backward tensor([0.4995, 0.0000])
current_lr 0.001
loss tensor(0.0092, grad_fn=<MeanBackward0>)
before backward tensor([0.4995, 0.0000])
after backward tensor([0.4995, 0.0000])
current_lr 0.001
loss tensor(0.0091, grad_fn=<MeanBackward0>)
before backward tensor([0.4995, 0.0000])
after backward tensor([0.4995, 0.0000])
current_lr 0.001
loss tensor(0.0090, grad_fn=<MeanBackward0>)
before backward tensor([0.4995, 0.0000])
after backward tensor([0.4995, 0.0000])
current_lr 0.001